site_name: Distributed Scraping Network

theme:
  name: "material"

plugins:
   - swagger-ui-tag
   - mkdocstrings:
        default_handler: python

nav:
  - Home: index.md
  - API Documentation: api.md
