site_name: Distributed Scraping Network

theme:
  name: "material"

plugins:
   - swagger-ui-tag
   - mkdocstrings:
        default_handler: python

nav:
  - Organization Home: https://spatiotemporal-wildlife-classification.github.io/
  - Home: index.md
  - How to use: use.md
  - API Documentation: api.md
